### ISSUE TITLE
Fix layout 

### ISSUE THREAD

**Issue by mhstrkmp** [a-friday-with-donald/tronalddump-api#32]
- not possible to play on a small screen
- page doesn’t grow or scrolling down is not correct
- after initial loading the rest of the page is cutting off 
- looks like a problem with the background as you can click a button at the white area. You just can’t see what you’re clicking cause the background is not growing accordingly. 
- screenshot made with an iPhone SE 2020

![F27470CB-227B-45AE-B640-C3433B7910C5](https://user-images.githubusercontent.com/5558193/97122408-e9487200-1725-11eb-8055-6947cd5d62a6.png)

**Comment by athnme** [comment]
I worked on the layout and tried and created a pull request before reading this issue. I looked again at the stuff I have tweaked and I think this white clipping issue shouldn't be a problem anymore. I checked on different screen sizes if the issue is still persists  but wasn't able to reproduce the problem after the tweaks. Still, you guys might want to take a look at the pull request before merging it. Better safe than sorry.

Here is the link to the pull request: https://github.com/a-friday-with-donald/tronalddump-api/pull/33
